// GENERATED by scripts/gen-examples.mjs from playground/examples/*.vl — do not edit.
window.VILAN_EXAMPLES = {
	"counter": "// A reactive counter: the signal is the state, the markup follows it.\n// Change the label, add a second button — then press Run.\n\nfun main() {\n\tui::mount_root(\"app\", || {\n\t\tlet count = Signal::new(0);\n\t\t<div>\n\t\t\t<h2>\"Counter\"</h2>\n\t\t\t<button on:click(|| count.set(count.get() + 1))>\"+1\"</button>\n\t\t\t<p>{count.derive(|n| i\"clicked {n} times\")}</p>\n\t\t</div>\n\t});\n}\n",
	"hello": "// Hello: build a view, mount it, print to the console pane.\n\nfun main() {\n\tprint(\"Hello from the vilan playground!\");\n\tui::mount(\"app\", <h1>\"Hello, world\"</h1>);\n}\n",
	"server": "// A typed HTTP service: the same language, the process leg. Server mode\n// TYPECHECKS this (platform coloring is the check; flip the mode to Browser\n// to watch it refuse); running it for real takes a process host:\n// `vilan init my-app && vilan run my-app`.\n\nimport std::http::{ Response, Server };\n\nasync fun main() {\n\tServer::builder()\n\t\t.port(3000)\n\t\t.on_request(|request| {\n\t\t\tResponse::builder().body(i\"hello from {request.path()}\").build()\n\t\t})\n\t\t.on_start(|server| print(i\"listening at {server.url()}\"))\n\t\t.build()\n\t\t.start();\n}\n",
	"styles": "// Styles are compiled, not shipped: each `css { … }` block is a style the\n// compiler turns into stylesheet rules at build time, and the classes below\n// are their hashed names.\n\nlet card = css {\n\tpadding(space(6));\n\tcolor(hex(\"#F9DFE7\"));\n\tbackground(hex(\"#1B060D\"));\n\tborder-radius(px(12));\n};\n\nlet title = css {\n\tmargin(space(0));\n\tcolor(hex(\"#EB682E\"));\n};\n\nfun main() {\n\tlet _root = ui::mount_root(\"app\", || {\n\t\t<div .styled(card)>\n\t\t\t<h2 .styled(title)>\"Styled at compile time\"</h2>\n\t\t\t<p>\"This card's CSS came out of the compiler.\"</p>\n\t\t</div>\n\t});\n}\n",
};
// Fingerprints (playground/fingerprint.js) of every example text the playground
// shipped and has since replaced: a restored buffer matching one is swapped for
// the current example (scripts/gen-examples.mjs says why).
window.VILAN_RETIRED_EXAMPLES = {
	"032a5e942eb099": "server",
	"03f610205202ee": "styles",
	"0ae22b1be71d03": "counter",
	"0b728bb6227dc2": "server",
	"0f0a2211f17df5": "server",
	"133b0e12172667": "hello",
	"148f9fff184497": "styles",
	"16a5c966936d49": "hello",
	"1907ab32263c5e": "styles",
	"1a96216090bf87": "hello",
	"1b382127fd081c": "counter",
	"1ce991852812e5": "styles",
	"1e88fc1ef2aa91": "counter",
	"1fb0403c7c283e": "hello",
	"1fe6ef53e1e544": "styles",
};
