// Bundle editor.mjs (with its CodeMirror dependency tree) into the committed
// playground/editor.js: one IIFE, no imports left, nothing fetched at runtime.
import { build } from "esbuild";

await build({
	entryPoints: ["editor.mjs"],
	bundle: true,
	minify: true,
	format: "iife",
	target: ["es2021"],
	outfile: "../editor.js",
	banner: {
		js: "/* GENERATED by playground/editor-src (esbuild) - do not edit; see editor-src/editor.mjs */",
	},
});
console.log("wrote playground/editor.js");
