// Bundle editor.mjs (with its CodeMirror dependency tree) into the committed
// src/playground/editor.js: one IIFE, no imports left, nothing fetched at
// runtime. It sits under src/ because the playground leg bundles it —
// `const asset::bundle` resolves against the package root.
import { build } from "esbuild";

await build({
	entryPoints: ["editor.mjs"],
	bundle: true,
	minify: true,
	format: "iife",
	target: ["es2021"],
	outfile: "../../src/playground/editor.js",
	banner: {
		js: "/* GENERATED by playground/editor-src (esbuild) - do not edit; see editor-src/editor.mjs */",
	},
});
console.log("wrote src/playground/editor.js");
