// GENERATED by scripts/gen-keywords.mjs from `vilan --print-keywords` — do not edit.
// The compiler's keyword table (lexing::KEYWORDS + CONTEXTUAL_KEYWORDS), split
// into the words that are ALWAYS keywords and the ones that are keywords only by
// position; tests/keywords.test.mjs holds this file to the installed compiler.

export const RESERVED = ["async", "await", "const", "css", "else", "enum", "export", "external", "false", "for", "fun", "if", "impl", "import", "in", "is", "let", "macro", "match", "mod", "mut", "null", "ret", "struct", "trait", "true", "type", "use"];

export const CONTEXTUAL = ["Self", "as", "auto", "borrows", "context", "dyn", "jump", "lazy", "only", "own", "self", "sync", "then", "void", "with"];
